version: '3.8'

services:
  front-cs-community:
    container_name: front-cs-community
    # The official v2 Traefik docker image
    image: simachille/front-cs-community:latest
    restart: always
    ports:
      # The HTTP port
      - '83:3000'

    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network
